lookup:
    replace-map:
        14: 7

spring:
  datasource:
    url: jdbc:h2:mem:SNOMEDUMLS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop


umls.mrconso.headers: ['cui', 'lat', 'ts', 'lui', 'stt', 'sui', 'ispref', 'aui', 'saui', 'scui', 'sdui', 'sab', 'tty', 'code', 'str', 'srl', 'suppress', 'cvf']